#!/system/bin/sh
# mmontuori MROM changes
 
if grep olympus /proc/cpuinfo>/dev/null; then
        echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
        echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
fi

